blogs/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(success_url=reverse_lazy('blogs:password_change_done')), name='password_change'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_post/<str:post_type>', views.create_post, name='create_post'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:post_id>/<str:post_type>', views.post_detail, name='post_detail'),
    path('delete_post/<int:post_id>/<str:post_type>', views.delete_post, name='delete_post'),
    path('about_user/', views.about_user, name='about_user'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('post_search/', views.search_posts, name='post_search')
]

fusionpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('', RedirectView.as_view(url='/blogs/', permanent=True))
]

blogs/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from storages.backends.s3boto3 import S3Boto3Storage
from django.core.validators import FileExtensionValidator

class TextPost(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_text_posts')
    image = models.FileField(blank=True,
                            storage=S3Boto3Storage(),
                            upload_to='posts/%Y/%m/%d/'
                            )
    title = models.CharField(max_length=50)
    body = models.CharField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]
    
    def __str__(self):
        return self.title


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20)
    avatar = models.FileField(storage=S3Boto3Storage(),
                              upload_to='users/%Y/%m/%d/',
                              blank=True,
                                validators=[
                                    FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg'])
                                ]
                            )

    def __str__(self):
        return self.username


class Comment(models.Model):
    post = models.ForeignKey(TextPost, on_delete=models.CASCADE, related_name='blog_text_comment')
    author = models.CharField()
    title = models.CharField(max_length=100)
    body = models.CharField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]
    

    def __str__(self):
        return f"От {self.author} для {self.title}"


class PhotoForGallery(models.Model):
    image = models.FileField(
        storage=S3Boto3Storage(),
        upload_to='gallery/%Y/%m/%d/',
        validators=[
            FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg', 'mp4', 'mov', 'mkv', 'avi'])
            ]
        )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='photos_from_gallery')
    publish = models.DateTimeField(default=timezone.now)

blogs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import TextPost, CustomUser, Comment, PhotoForGallery

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'phone', 'password1', 'password2', 'avatar']
        labels = {
            'username': "Имя пользователя",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "password1": "Пароль",
            "password2": "Повторите пароль",
            "email": "E-Mail"
            }


class TextPostForm(forms.ModelForm):
    class Meta:
        model = TextPost
        fields = ['image', 'title', 'body', 'private']
        widgets = {'body': forms.Textarea}
        labels = {"title": "Название", "body": "Текст", "Изображение": "image", "Приватный": "private"}


class EditUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'avatar']
        labels = {
            "username": "Имя пользователя",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "email": "E-Mail",
            "phone": "Номер телефона"
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'body']
        labels = {"title": "Название", "body": "Текст"}
    

class PhotoForGalleryForm(forms.ModelForm):
    class Meta:
        model = PhotoForGallery
        fields = ['image']
        labels = {'image': 'Загрузить фотографию 📷'}

class SearchForm(forms.Form):
    query = forms.CharField()

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.core.paginator import Paginator
from django.contrib.postgres.search import SearchVector
from .forms import RegistrationForm, TextPostForm, EditUserForm, CommentForm, SearchForm
from .models import TextPost, CustomUser, Comment, PhotoForGallery
from .parameters import get_params_for_createobject, get_params_for_getobject
from django.http import Http404
from django.db.models import Q

def index(request):
    if request.user.is_authenticated:
        post_list = TextPost.objects.filter(Q(private=False) | Q(author=request.user))
    else:
        post_list = TextPost.objects.filter(private=False)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "index.html", {"page_obj": page_obj})

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            login(request, form.save())
            return redirect('blogs:post_list')
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

@login_required
def create_post(request, post_type):
    post_params = get_params_for_createobject(request.POST, request.FILES)
    if request.method == 'POST':
        form = post_params["forms_by_tags"][post_type][0]
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            match post_type:
                case "text_post":
                    return redirect('blogs:post_list')
                case "photo_gallery":
                    return redirect("blogs:create_post", post_type=post_type)
    else:
        form = post_params["forms_by_tags"][post_type][1]

    template = post_params["templates_by_post_type"][post_type]

    template_params = {'form': form,
                       "header": post_params["headers"][post_type],
                       "photos": PhotoForGallery.objects.filter(author=request.user)}
    return render(request, template, template_params)

@login_required
def post_list(request):
    return render(request, 'posts/post_list.html', {"posts": TextPost.objects.filter(author=request.user)})

@login_required
def delete_post(request, post_id, post_type):
    post_params = get_params_for_getobject()
    post_params[post_type].objects.filter(id=post_id).delete()
    match post_type:
        case "text_post":
            return redirect('blogs:post_list')
        case "photo_gallery":
            return redirect('blogs:create_post', post_type=post_type)

def post_detail(request, post_id, post_type):
    post_params = get_params_for_getobject()
    post = post_params[post_type].objects.get(id=post_id)

    is_unauthorized = post.author != request.user
    is_private_text = post_type == 'text_post' and post.private
    is_photo_gallery = post_type == 'photo_gallery'
    if is_unauthorized and (is_private_text or is_photo_gallery):
            raise Http404("Запись не найдена или недоступна")
    
    comments, comment_form = None, None
    if post_type == "text_post":
        comments = Comment.objects.filter(post=post)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
        else:
            comment_form = CommentForm()

    params = {"post": post, "comments": comments, "comment_form": comment_form, "post_type": post_type}
    return render(request, 'posts/post_detail.html', params)

@login_required
def edit_post(request, post_id):
    text_post = TextPost.objects.get(id=post_id)
    if request.method == 'POST':
        edit_form = TextPostForm(request.POST, request.FILES, instance=text_post)
        if edit_form.is_valid():
            edit_form.save()
            return redirect('blogs:post_detail', post_id=text_post.id, post_type="text_post")
    else:
        edit_form = TextPostForm(instance=text_post)
    return render(request, 'posts/edit_post.html', {'text_post': text_post, 'edit_form': edit_form})

@login_required
def about_user(request): 
    return render(request, 'about_user.html', {"user": CustomUser.objects.get(id=request.user.id)})

@login_required
def edit_user(request):
    if request.method == "POST":
        userform = EditUserForm(request.POST, request.FILES, instance=request.user)
        if userform.is_valid():
            userform.save()
            return redirect('blogs:about_user')
    else:
        userform = EditUserForm(instance=request.user)
    return render(request, 'edit_user.html', {"userform": userform})


def search_posts(request):
    query = None
    form = SearchForm()
    result = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search_vector = SearchVector('title', 'body', config='russian')
            query = form.cleaned_data['query']
            if request.user.is_authenticated:
                result = TextPost.objects.annotate(search=search_vector
                                                   ).filter(Q(search=query) & (Q(author=request.user) | Q(private=False)))
            else:
                result = TextPost.objects.annotate(search=search_vector).filter(Q(search=query) & Q(private=False))
    return render(request, 'posts/post_search.html', {'result': result, 'query': query, 'form': form})

 

blogs/templates/posts/create_text_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ header }}{% endblock %}

{% block body %}
    <h1>{{ header }}</h1>
    <br><br>
    <form method="post" action="{% url "blogs:create_post" "text_post" %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-success" type="submit" value="Делать">
    </form>
{% endblock %}

blogs/templates/posts/edit_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Редактировать {{ text_post.title }}{% endblock %}

{% block body %}
    <h1>Редактировать пост "{{ text_post.title }}"</h1>
    <form method="post" action="{% url "blogs:edit_post" text_post.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{edit_form|crispy }}
        <input type="submit" class="btn btn-success" value="Редактировать">
    </form>
{% endblock %}

blogs/templates/posts/post_detail.html
{% extends "base.html" %}
{% load blogs_tags %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block body %}
    <h1>{{ post.title }}</h1>
    <br><br>
    {% if post.image %}
        {% get_content_type post.image.name as content_type %}
        {% if content_type.is_image %}
            <img src="{{ post.image.url }}" width="500">
        {% elif content_type.is_video %}
            <video src="{{ post.image.url }}" width="450" controls></video>
        {% elif content_type.is_audio %}
            <audio src="{{ post.image.url }}" controls></audio>
        {% else %}
            <a href="{{ post.image.url }}" download>Скачать {% image_name_without_path post.id post_type %}</a>
        {% endif %}
    {% endif %}
    <br><br>
    {% if post.body %}
            <div class="border border-black rounded-3">
                <pre>{{ post.body }}</pre>
            </div>
    {% endif %}
    <br><br>
    <div class="alert alert-info" role="alert">
        <ul>
            <li>Опубликован: {{ post.publish }} </li>
            <li>Опубликовал: {{ post.author }}</li>
            {% if post.image %}
                <li>Название файла: {% image_name_without_path post.id post_type %}</li>
                <li>Размер файла: {% get_image_size_in_megabytes post.id post_type %} МБ</li>
                {% if content_type.is_image %}
                    <li>Размер изображения: {% get_image_width_height post.id post_type %}</li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
    <br><br>
    {% if post_type == "photo_gallery" %}
        <a href="{% url "blogs:delete_post" post.id post_type %}" class="btn btn-danger">Удалить пост</a>
    {% endif %}
    <br><br><br><br><br>
    <br><br><br><br><br>
    {% if post_type == "text_post" %}
        {% if comments %}
            <ol class="list-group list-group-numbered">
                {% for comment in comments %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ comment.title }} от {{comment.author}}</div>
                        {{ comment.body }}
                    </div>
                    <span class="badge text-bg-primary rounded-pill">{{ comment.publish }}</span>
                    </li>
                {% endfor %}
            </ol>
        {% else %}
        <div class="alert alert-dark" role="alert">
            Пока никто не оставил коментарий
        </div>
        {% endif %}
        <br><br><br>
        {% if request.user.is_authenticated %}
            <h3>Оставить коментарий</h3>
            <form action="{% url "blogs:post_detail" post.id post_type %}" method="post">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" class="btn btn btn-success" value="Оставить коментарий">
            </form>
        {% else %}
            <div class="alert alert-warning" role="alert">
                Чтобы оставить коментарий, пожалуйста зарегестрируйтесь
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

blogs/templates/posts/post_list.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block body %}
    <h1>Список постов</h1>
    <br><br>
    <a class="btn btn-outline-primary" href="{% url "blogs:create_post" "text_post" %}">Создать текстовый пост</a>
    <br><br>
    <div class="list-group">
        {% for post in posts %}
            <a href="{% url "blogs:post_detail" post.id "text_post" %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ post.title }}</h5>
                    <small class="text-body-secondary">{{ post.publish }}</small>
                </div>
                <p class="mb-1">{{ post.body|truncatewords:30 }}</p>
                <a href="{% url "blogs:delete_post" post.id "text_post" %}">Удалить</a>
                <a href="{% url "blogs:edit_post" post.id %}">Редактировать</a>
            </a>
        {% endfor %}
      </div>
{% endblock %}

blogs/templates/posts/post_search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Найти{% endblock %}

{% block body %}
    <h1>Найти пост</h1>
    <br>
    <form method="get">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Найти">
    </form>
    <br>
    {% if query %}
        {% for post in result %}
            <h4><a href="{% url "blogs:post_detail" post.id "text_post" %}">{{forloop.counter}}. {{ post }} от {{ post.author }}</a></h4>
            {{ post.body|truncatewords:30 }}
            <br><br>
            --------------------------------------------------------------------------------------------------
        {% endfor %}
    {% endif %}
{% endblock %}