blogs/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_change/', PasswordChangeView.as_view(success_url=reverse_lazy('blogs:password_change_done')), name='password_change'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_post/<str:post_type>', views.create_post, name='create_post'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:post_id>/<str:post_type>', views.post_detail, name='post_detail'),
    path('delete_post/<int:post_id>/<str:post_type>', views.delete_post, name='delete_post'),
    path('about_user/', views.about_user, name='about_user'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('post_search/', views.search_posts, name='post_search')
]

fusionpost/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('', RedirectView.as_view(url='/blogs/', permanent=True))
]

blogs/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from storages.backends.s3boto3 import S3Boto3Storage
from django.core.validators import FileExtensionValidator

class TextPost(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_text_posts')
    image = models.FileField(blank=True,
                            storage=S3Boto3Storage(),
                            upload_to='posts/%Y/%m/%d/'
                            )
    title = models.CharField(max_length=50)
    body = models.CharField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    private = models.BooleanField(default=False)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]
    
    def __str__(self):
        return self.title


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20)
    avatar = models.FileField(storage=S3Boto3Storage(),
                              upload_to='users/%Y/%m/%d/',
                              blank=True,
                                validators=[
                                    FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg'])
                                ]
                            )

    def __str__(self):
        return self.username


class Comment(models.Model):
    post = models.ForeignKey(TextPost, on_delete=models.CASCADE, related_name='blog_text_comment')
    author = models.CharField()
    title = models.CharField(max_length=100)
    body = models.CharField()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]
    

    def __str__(self):
        return f"От {self.author} для {self.title}"


class PhotoForGallery(models.Model):
    image = models.FileField(
        storage=S3Boto3Storage(),
        upload_to='gallery/%Y/%m/%d/',
        validators=[
            FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bmp', 'jpeg', 'mp4', 'mov', 'mkv', 'avi'])
            ]
        )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='photos_from_gallery')
    publish = models.DateTimeField(default=timezone.now)

blogs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import TextPost, CustomUser, Comment, PhotoForGallery

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'first_name', 'last_name', 'phone', 'password1', 'password2', 'avatar']
        labels = {
            'username': "Имя пользователя",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "password1": "Пароль",
            "password2": "Повторите пароль",
            "email": "E-Mail"
            }


class TextPostForm(forms.ModelForm):
    class Meta:
        model = TextPost
        fields = ['image', 'title', 'body', 'private']
        widgets = {'body': forms.Textarea}
        labels = {"title": "Название", "body": "Текст", "Изображение": "image", "Приватный": "private"}


class EditUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'avatar']
        labels = {
            "username": "Имя пользователя",
            "first_name": "Имя",
            "last_name": "Фамилия",
            "email": "E-Mail",
            "phone": "Номер телефона"
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'body']
        labels = {"title": "Название", "body": "Текст"}
    

class PhotoForGalleryForm(forms.ModelForm):
    class Meta:
        model = PhotoForGallery
        fields = ['image']
        labels = {'image': 'Загрузить фотографию 📷'}

class SearchForm(forms.Form):
    query = forms.CharField()

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.core.paginator import Paginator
from django.contrib.postgres.search import SearchVector
from .forms import RegistrationForm, TextPostForm, EditUserForm, CommentForm, SearchForm
from .models import TextPost, CustomUser, Comment, PhotoForGallery
from .parameters import get_params_for_createobject, get_params_for_getobject
from django.http import Http404
from django.db.models import Q

def index(request):
    if request.user.is_authenticated:
        post_list = TextPost.objects.filter(Q(private=False) | Q(author=request.user))
    else:
        post_list = TextPost.objects.filter(private=False)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "index.html", {"page_obj": page_obj})

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            login(request, form.save())
            return redirect('blogs:post_list')
    else:
        form = RegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

@login_required
def create_post(request, post_type):
    post_params = get_params_for_createobject(request.POST, request.FILES)
    if request.method == 'POST':
        form = post_params["forms_by_tags"][post_type][0]
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            match post_type:
                case "text_post":
                    return redirect('blogs:post_list')
                case "photo_gallery":
                    return redirect("blogs:create_post", post_type=post_type)
    else:
        form = post_params["forms_by_tags"][post_type][1]

    template = post_params["templates_by_post_type"][post_type]

    template_params = {'form': form,
                       "header": post_params["headers"][post_type],
                       "photos": PhotoForGallery.objects.filter(author=request.user)}
    return render(request, template, template_params)

@login_required
def post_list(request):
    return render(request, 'posts/post_list.html', {"posts": TextPost.objects.filter(author=request.user)})

@login_required
def delete_post(request, post_id, post_type):
    post_params = get_params_for_getobject()
    post_params[post_type].objects.filter(id=post_id).delete()
    match post_type:
        case "text_post":
            return redirect('blogs:post_list')
        case "photo_gallery":
            return redirect('blogs:create_post', post_type=post_type)

def post_detail(request, post_id, post_type):
    post_params = get_params_for_getobject()
    post = post_params[post_type].objects.get(id=post_id)

    is_unauthorized = post.author != request.user
    is_private_text = post_type == 'text_post' and post.private
    is_photo_gallery = post_type == 'photo_gallery'
    if is_unauthorized and (is_private_text or is_photo_gallery):
            raise Http404("Запись не найдена или недоступна")
    
    comments, comment_form = None, None
    if post_type == "text_post":
        comments = Comment.objects.filter(post=post)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = request.user
                comment.post = post
                comment.save()
        else:
            comment_form = CommentForm()

    params = {"post": post, "comments": comments, "comment_form": comment_form, "post_type": post_type}
    return render(request, 'posts/post_detail.html', params)

@login_required
def edit_post(request, post_id):
    text_post = TextPost.objects.get(id=post_id)
    if request.method == 'POST':
        edit_form = TextPostForm(request.POST, request.FILES, instance=text_post)
        if edit_form.is_valid():
            edit_form.save()
            return redirect('blogs:post_detail', post_id=text_post.id, post_type="text_post")
    else:
        edit_form = TextPostForm(instance=text_post)
    return render(request, 'posts/edit_post.html', {'text_post': text_post, 'edit_form': edit_form})

@login_required
def about_user(request): 
    return render(request, 'about_user.html', {"user": CustomUser.objects.get(id=request.user.id)})

@login_required
def edit_user(request):
    if request.method == "POST":
        userform = EditUserForm(request.POST, request.FILES, instance=request.user)
        if userform.is_valid():
            userform.save()
            return redirect('blogs:about_user')
    else:
        userform = EditUserForm(instance=request.user)
    return render(request, 'edit_user.html', {"userform": userform})


def search_posts(request):
    query = None
    form = SearchForm()
    result = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            search_vector = SearchVector('title', 'body', config='russian')
            query = form.cleaned_data['query']
            if request.user.is_authenticated:
                result = TextPost.objects.annotate(search=search_vector
                                                   ).filter(Q(search=query) & (Q(author=request.user) | Q(private=False)))
            else:
                result = TextPost.objects.annotate(search=search_vector).filter(Q(search=query) & Q(private=False))
    return render(request, 'posts/post_search.html', {'result': result, 'query': query, 'form': form})

 

blogs/templates/about_user.html
{% extends "base.html" %}

{% block title %}О вас{% endblock %}

{% block body %}
    <h1>О вас {{user.username}}</h1>
    <br><br>
    {% if user.avatar %}
      <div class="border border-success border-2" style="float: left;">
          <img src="{{user.avatar.url}}"  width="200" >
      </div>
    {% endif %}
    <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Имя</div>
            {{user.username}}
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Почта</div>
            {{user.email}}
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Номер телефона</div>
            {{user.phone}}
          </div>
        </li>
      </ol>
      <br>
      <a href="{% url "blogs:edit_user" %}" class="btn btn-warning">Редактировать профиль</a>
{% endblock %}

blogs/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="yandex-verification" content="e580257e98620f43" />
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&family=M+PLUS+Rounded+1c:wght@500&display=swap" rel="stylesheet">
        <link href="{% static "css/styles.css" %}" rel="stylesheet">
        <link rel="icon" href="{% static "images/favicon.png" %}" type="image/png">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url "blogs:index" %}">FusionPost</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="{% url "blogs:dashboard" %}">Панель управления</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "blogs:about_user" %}">О вас</a>
                                </li>
                                <form action="{% url "blogs:logout" %}" method="post">
                                    <button class="nav-link" type="submit">Выйти</button>
                                    {% csrf_token %}
                                </form>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "blogs:login" %}">Войти</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url "blogs:register" %}">Зарегистрироваться</a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "blogs:post_search" %}">Найти</a>
                            </li>
                        </ul>
                    </div>
            </div>
          </nav>
        <div class="container">
            {% block body %}{% endblock %}
            <br><br><br><br><br><br><br><br><br>
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
              <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-body-secondary">© 2025 Goyda, Inc</span>
              </div>
            </footer>
        </div>
    </body>
</html>

blogs/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Добро пожаловать{% endblock %}

{% block body %}
    <h1>Добро пожаловать {{request.user}} Выберите действие</h1>
    <br><br>
    <div class="list-group">
        <a href="{% url "blogs:post_list" %}" class="list-group-item list-group-item-action list-group-item-info">Список текстовых постов</a>
        <a href="{% url "blogs:create_post" "photo_gallery" %}" class="list-group-item list-group-item-action list-group-item-warning">Галерея</a>
    </div>
{% endblock %}

blogs/templates/edit_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Редактировать профиль{% endblock %}

{% block body %}
    <h1>Редактировать профиль</h1>
    <br><br>
    <form method="post" enctype="multipart/form-data" action="{% url "blogs:edit_user" %}">
        {% csrf_token %}
        {{ userform|crispy }}
        <input class="btn btn-success" type="submit" value="Редактировать">
    </form>
    <br>
    <a href="{% url "blogs:password_change" %}" class="btn btn-danger">Сменить пароль</a>
{% endblock %}

blogs/templates/index.html
{% extends "base.html" %}

{% block title %}Главная{% endblock %}
{% block body %}
    <h1>Главная</h1>
    <br><br>
    <div class="list-group">
        {% for post in page_obj %}
            <a href="{% url "blogs:post_detail" post.id "text_post" %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ post.title }}</h5>
                    <small class="text-body-secondary">{{ post.publish }}</small>
                    <small class="text-body-secondary">{{ post.author }}</small>
                </div>
                <p class="mb-1">{{ post.body|truncatewords:30 }}</p>
            </a>
        {% endfor %}
    </div>
    <br><br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for page in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
{% endblock %}